In [5]:
import intake_esgf
intake_esgf.conf.set(local_cache=["."])

In [1]:
from intake_esgf import ESGFCatalog

In [2]:
cat = ESGFCatalog()

In [3]:
cat.variable_info("temperature")

,variable_units,variable_long_name,cf_standard_name
variable_id,,,
sitemptop,K,snow/ice surface temperature,sea_ice_surface_temperature
ta,K,Air Temperature,air_temperature
ta850,K,Air Temperature,air_temperature
tas,K,Near-Surface Air Temperature,air_temperature
tasmax,K,Daily Maximum Near-Surface Air Temperature,air_temperature
tasmin,K,Daily Minimum Near-Surface Air Temperature,air_temperature
thetao,degC,Sea Water Potential Temperature,sea_water_potential_temperature
tos,degC,Sea Surface Temperature,sea_surface_temperature
ts,K,Surface Temperature,surface_temperature
tsl,K,Temperature of Soil,soil_temperature

In [37]:
cat.variable_info("optical depth")

,cf_standard_name,variable_units,variable_long_name
variable_id,,,
abs550aer,atmosphere_absorption_optical_thickness_due_to...,1,Ambient Aerosol Absorption Optical Thickness a...
bldep,atmosphere_boundary_layer_thickness,m,Boundary Layer Depth
deptho,sea_floor_depth_below_geoid,m,Sea Floor Depth Below Geoid
od550aer,atmosphere_optical_thickness_due_to_ambient_ae...,1,Ambient Aerosol Optical Thickness at 550nm
snd,surface_snow_thickness,m,Snow Depth
t20d,depth_of_isosurface_of_sea_water_potential_tem...,m,20C isotherm depth
thetaot2000,sea_water_potential_temperature,degC,Depth Average Potential Temperature of Upper 2...
thetaot300,sea_water_potential_temperature,degC,Depth Average Potential Temperature of Upper 300m
thetaot700,sea_water_potential_temperature,degC,Depth Average Potential Temperature of Upper 700m
zo2min,depth_at_shallowest_local_minimum_in_vertical_...,m,Depth of Oxygen Minimum Concentration

In [75]:
cat.search(
    activity_id="DAMIP",
    variable_id=["rlut", "rsut"],
    experiment_id="hist-aer",
    source_id="HadGEM3-GC31-LL",
    member_id="r1i1p1f3", # forcing 3 specific for HadGEM3
    table_id="Amon"
)

   Searching indices:   0%|          |0/1 [       ?index/s]

Summary information for 2 results:
mip_era                     [CMIP6]
activity_drs                [DAMIP]
institution_id               [MOHC]
source_id         [HadGEM3-GC31-LL]
experiment_id            [hist-aer]
member_id                [r1i1p1f3]
table_id                     [Amon]
variable_id            [rlut, rsut]
grid_label                     [gn]
dtype: object

In [26]:
dsd = cat.to_dataset_dict()

Get file information:   0%|          |0/1 [       ?index/s]

Downloading 158.5 [Mb]...

rsut_Amon_HadGEM3-GC31-LL_hist-aer_r1...:   0%|          |0.00/65.8M [?B/s]

rsut_Amon_HadGEM3-GC31-LL_hist-aer_r1...:   0%|          |0.00/92.7M [?B/s]

Adding cell measures:   0%|          |0/2 [     ?dataset/s]

Address Gan's recommendation (look at surface temp trend for `hist-aer` `hist-nat` for 3-5 models)

In [4]:
g = cat.search(
    activity_id="DAMIP",
    activity_drs="DAMIP",
    variable_id="tas",
    experiment_id=["hist-aer", "hist-nat"],
    #source_id="HadGEM3-GC31-LL",
    member_id="r1i1p1f1", # forcing 3 specific for HadGEM3
    table_id="Amon"
)

   Searching indices:   0%|          |0/1 [       ?index/s]

In [5]:
g.df

,project,mip_era,activity_drs,institution_id,source_id,experiment_id,member_id,table_id,variable_id,grid_label,version,id
0,CMIP6,CMIP6,DAMIP,BCC,BCC-CSM2-MR,hist-aer,r1i1p1f1,Amon,tas,gn,20190507,[CMIP6.DAMIP.BCC.BCC-CSM2-MR.hist-aer.r1i1p1f1...
4,CMIP6,CMIP6,DAMIP,BCC,BCC-CSM2-MR,hist-nat,r1i1p1f1,Amon,tas,gn,20190426,[CMIP6.DAMIP.BCC.BCC-CSM2-MR.hist-nat.r1i1p1f1...
8,CMIP6,CMIP6,DAMIP,CAS,FGOALS-g3,hist-aer,r1i1p1f1,Amon,tas,gn,20200411,[CMIP6.DAMIP.CAS.FGOALS-g3.hist-aer.r1i1p1f1.A...
12,CMIP6,CMIP6,DAMIP,CAS,FGOALS-g3,hist-nat,r1i1p1f1,Amon,tas,gn,20200411,[CMIP6.DAMIP.CAS.FGOALS-g3.hist-nat.r1i1p1f1.A...
16,CMIP6,CMIP6,DAMIP,CCCma,CanESM5,hist-aer,r1i1p1f1,Amon,tas,gn,20190429,[CMIP6.DAMIP.CCCma.CanESM5.hist-aer.r1i1p1f1.A...
20,CMIP6,CMIP6,DAMIP,CCCma,CanESM5,hist-nat,r1i1p1f1,Amon,tas,gn,20190429,[CMIP6.DAMIP.CCCma.CanESM5.hist-nat.r1i1p1f1.A...
24,CMIP6,CMIP6,DAMIP,CSIRO-ARCCSS,ACCESS-CM2,hist-aer,r1i1p1f1,Amon,tas,gn,20201120,[CMIP6.DAMIP.CSIRO-ARCCSS.ACCESS-CM2.hist-aer....
27,CMIP6,CMIP6,DAMIP,CSIRO-ARCCSS,ACCESS-CM2,hist-nat,r1i1p1f1,Amon,tas,gn,20201120,[CMIP6.DAMIP.CSIRO-ARCCSS.ACCESS-CM2.hist-nat....
30,CMIP6,CMIP6,DAMIP,CSIRO,ACCESS-ESM1-5,hist-aer,r1i1p1f1,Amon,tas,gn,20200615,[CMIP6.DAMIP.CSIRO.ACCESS-ESM1-5.hist-aer.r1i1...
33,CMIP6,CMIP6,DAMIP,CSIRO,ACCESS-ESM1-5,hist-nat,r1i1p1f1,Amon,tas,gn,20200615,[CMIP6.DAMIP.CSIRO.ACCESS-ESM1-5.hist-nat.r1i1...
36,CMIP6,CMIP6,DAMIP,E3SM-Project,E3SM-2-0,hist-aer,r1i1p1f1,Amon,tas,gr,20220905,[CMIP6.DAMIP.E3SM-Project.E3SM-2-0.hist-aer.r1...
38,CMIP6,CMIP6,DAMIP,E3SM-Project,E3SM-2-0,hist-nat,r1i1p1f1,Amon,tas,gr,20230104,[CMIP6.DAMIP.E3SM-Project.E3SM-2-0.hist-nat.r1...
40,CMIP6,CMIP6,DAMIP,IPSL,IPSL-CM6A-LR,hist-aer,r1i1p1f1,Amon,tas,gr,20180914,[CMIP6.DAMIP.IPSL.IPSL-CM6A-LR.hist-aer.r1i1p1...
43,CMIP6,CMIP6,DAMIP,IPSL,IPSL-CM6A-LR,hist-nat,r1i1p1f1,Amon,tas,gr,20180914,[CMIP6.DAMIP.IPSL.IPSL-CM6A-LR.hist-nat.r1i1p1...
46,CMIP6,CMIP6,DAMIP,MIROC,MIROC6,hist-aer,r1i1p1f1,Amon,tas,gn,20190705,[CMIP6.DAMIP.MIROC.MIROC6.hist-aer.r1i1p1f1.Am...
49,CMIP6,CMIP6,DAMIP,MIROC,MIROC6,hist-nat,r1i1p1f1,Amon,tas,gn,20191114,[CMIP6.DAMIP.MIROC.MIROC6.hist-nat.r1i1p1f1.Am...
52,CMIP6,CMIP6,DAMIP,MRI,MRI-ESM2-0,hist-aer,r1i1p1f1,Amon,tas,gn,20190320,[CMIP6.DAMIP.MRI.MRI-ESM2-0.hist-aer.r1i1p1f1....
55,CMIP6,CMIP6,DAMIP,MRI,MRI-ESM2-0,hist-nat,r1i1p1f1,Amon,tas,gn,20190320,[CMIP6.DAMIP.MRI.MRI-ESM2-0.hist-nat.r1i1p1f1....
58,CMIP6,CMIP6,DAMIP,NASA-GISS,GISS-E2-1-G,hist-aer,r1i1p1f1,Amon,tas,gn,20180821,[CMIP6.DAMIP.NASA-GISS.GISS-E2-1-G.hist-aer.r1...
62,CMIP6,CMIP6,DAMIP,NASA-GISS,GISS-E2-1-G,hist-nat,r1i1p1f1,Amon,tas,gn,20180906,[CMIP6.DAMIP.NASA-GISS.GISS-E2-1-G.hist-nat.r1...
63,CMIP6,CMIP6,DAMIP,NCAR,CESM2,hist-aer,r1i1p1f1,Amon,tas,gn,20200206,[CMIP6.DAMIP.NCAR.CESM2.hist-aer.r1i1p1f1.Amon...
66,CMIP6,CMIP6,DAMIP,NCAR,CESM2,hist-nat,r1i1p1f1,Amon,tas,gn,20190730,[CMIP6.DAMIP.NCAR.CESM2.hist-nat.r1i1p1f1.Amon...
69,CMIP6,CMIP6,DAMIP,NCC,NorESM2-LM,hist-aer,r1i1p1f1,Amon,tas,gn,20190920,[CMIP6.DAMIP.NCC.NorESM2-LM.hist-aer.r1i1p1f1....
71,CMIP6,CMIP6,DAMIP,NCC,NorESM2-LM,hist-nat,r1i1p1f1,Amon,tas,gn,20190920,[CMIP6.DAMIP.NCC.NorESM2-LM.hist-nat.r1i1p1f1....
73,CMIP6,CMIP6,DAMIP,NOAA-GFDL,GFDL-CM4,hist-nat,r1i1p1f1,Amon,tas,gr1,20180701,[CMIP6.DAMIP.NOAA-GFDL.GFDL-CM4.hist-nat.r1i1p...
77,CMIP6,CMIP6,DAMIP,NOAA-GFDL,GFDL-ESM4,hist-aer,r1i1p1f1,Amon,tas,gr1,20180701,[CMIP6.DAMIP.NOAA-GFDL.GFDL-ESM4.hist-aer.r1i1...
81,CMIP6,CMIP6,DAMIP,NOAA-GFDL,GFDL-ESM4,hist-nat,r1i1p1f1,Amon,tas,gr1,20180701,[CMIP6.DAMIP.NOAA-GFDL.GFDL-ESM4.hist-nat.r1i1...

In [55]:
g.df['source_id'].sort_values().unique()

<ArrowStringArray>
[   'ACCESS-CM2', 'ACCESS-ESM1-5',   'BCC-CSM2-MR',         'CESM2',
       'CanESM5',      'E3SM-2-0',     'FGOALS-g3',      'GFDL-CM4',
     'GFDL-ESM4',   'GISS-E2-1-G',  'IPSL-CM6A-LR',        'MIROC6',
    'MRI-ESM2-0',    'NorESM2-LM']
Length: 14, dtype: str

Info via https://wcrp-cmip.org/cmip-model-and-experiment-documentation/#cmip6-2
| Model | Aerosol | Atmos Chem|
| ----- | ------- | --------- |
| ACCESS-CM2 | UKCA-GLOMAP-mode | none |
| CESM2 | MAM4 (same grid as atmos) | MAM4 (same grid as atmos) |
| E3SM-2-0 | MAM4 with new resuspension, marine organics, secondary organics, and dust (atmos grid) | Troposphere specified oxidants (except passive ozone with the lower boundary sink) for aerosols. Stratosphere linearized interactive ozone (LINOZ v2) (atmos grid) |
| GFDL-ESM4 | Interactive aerosol | GFDL-ATMCHEM4.1 (full atmospheric chemistry) |
| GISS-E2-1-G | varies with physics-version (p==1 none, p==3 OMA, p==4 TOMAS, p==5 MATRIX) | varies with physics-version (p==1 Non-interactive, p>1 GPUCCINI) |
| NorESM2-LM | OsloAero | OsloChemSimp |

In [57]:
g.df[g.df.source_id == 'GISS-E2-1-G']

,project,mip_era,activity_drs,institution_id,source_id,experiment_id,member_id,table_id,variable_id,grid_label,version,id
58,CMIP6,CMIP6,DAMIP,NASA-GISS,GISS-E2-1-G,hist-aer,r1i1p1f1,Amon,ts,gn,20180821,[CMIP6.DAMIP.NASA-GISS.GISS-E2-1-G.hist-aer.r1...
62,CMIP6,CMIP6,DAMIP,NASA-GISS,GISS-E2-1-G,hist-nat,r1i1p1f1,Amon,ts,gn,20180906,[CMIP6.DAMIP.NASA-GISS.GISS-E2-1-G.hist-nat.r1...

In [99]:
cat.search(
    activity_id="DAMIP",
    activity_drs="DAMIP",
    variable_id="ts",
    experiment_id=["hist-aer", "hist-nat"],
    source_id=['GISS-E2-1-G'],
    member_id="r1i1p1f1", 
    table_id="Amon"
)

dsd = cat.to_dataset_dict()

   Searching indices:   0%|          |0/1 [       ?index/s]

Get file information:   0%|          |0/1 [       ?index/s]

Downloading 205.5 [Mb]...

ts_Amon_GISS-E2-1-G_hist-nat_r1i1p1f1...:   0%|          |0.00/31.1M [?B/s]

ts_Amon_GISS-E2-1-G_hist-nat_r1i1p1f1...:   0%|          |0.00/31.8M [?B/s]

ts_Amon_GISS-E2-1-G_hist-nat_r1i1p1f1...:   0%|          |0.00/31.1M [?B/s]

ts_Amon_GISS-E2-1-G_hist-nat_r1i1p1f1...:   0%|          |0.00/8.73M [?B/s]

ts_Amon_GISS-E2-1-G_hist-aer_r1i1p1f1...:   0%|          |0.00/31.8M [?B/s]

ts_Amon_GISS-E2-1-G_hist-aer_r1i1p1f1...:   0%|          |0.00/31.1M [?B/s]

ts_Amon_GISS-E2-1-G_hist-aer_r1i1p1f1...:   0%|          |0.00/8.73M [?B/s]

ts_Amon_GISS-E2-1-G_hist-aer_r1i1p1f1...:   0%|          |0.00/31.1M [?B/s]

Adding cell measures:   0%|          |0/2 [     ?dataset/s]

In [96]:
cat.search(
    activity_id="DAMIP",
    activity_drs="DAMIP",
    variable_id="ts",
    experiment_id=["hist-nat"],
    source_id=['E3SM-2-0'],
    member_id="r1i1p1f1", 
    table_id="Amon"
)

dsd = cat.to_dataset_dict()

   Searching indices:   0%|          |0/1 [       ?index/s]

Get file information:   0%|          |0/1 [       ?index/s]

Downloading 111.6 [Mb]...

ts_Amon_E3SM-2-0_hist-nat_r1i1p1f1_gr...:   0%|          |0.00/112M [?B/s]

Adding cell measures:   0%|          |0/1 [     ?dataset/s]

In [102]:
cat.search(
    activity_id="DAMIP",
    activity_drs="DAMIP",
    variable_id=["rlut", "rsut"],
    experiment_id=["hist-aer", "hist-nat"],
    source_id=['ACCESS-CM2', 'CESM2', 'E3SM-2-0', 'GFDL-ESM4', 'NorESM2-LM', 'GISS-E2-1-G'],
    member_id="r1i1p1f1", 
    table_id="Amon"
)

dsd = cat.to_dataset_dict()

   Searching indices:   0%|          |0/1 [       ?index/s]

Get file information:   0%|          |0/1 [       ?index/s]

Downloading 5.4 [Gb]...

rlut_Amon_E3SM-2-0_hist-aer_r1i1p1f1_...:   0%|          |0.00/122M [?B/s]

rlut_Amon_ACCESS-CM2_hist-nat_r1i1p1f...:   0%|          |0.00/190M [?B/s]

rlut_Amon_ACCESS-CM2_hist-aer_r1i1p1f...:   0%|          |0.00/190M [?B/s]

rsut_Amon_ACCESS-CM2_hist-nat_r1i1p1f...:   0%|          |0.00/185M [?B/s]

rsut_Amon_ACCESS-CM2_hist-aer_r1i1p1f...:   0%|          |0.00/185M [?B/s]

rlut_Amon_E3SM-2-0_hist-aer_r1i1p1f1_...:   0%|          |0.00/122M [?B/s]

rsut_Amon_E3SM-2-0_hist-aer_r1i1p1f1_...:   0%|          |0.00/123M [?B/s]

rlut_Amon_E3SM-2-0_hist-nat_r1i1p1f1_...:   0%|          |0.00/122M [?B/s]

rlut_Amon_GISS-E2-1-G_hist-aer_r1i1p1...:   0%|          |0.00/31.8M [?B/s]

rlut_Amon_GISS-E2-1-G_hist-aer_r1i1p1...:   0%|          |0.00/31.1M [?B/s]

rlut_Amon_GISS-E2-1-G_hist-aer_r1i1p1...:   0%|          |0.00/31.1M [?B/s]

rlut_Amon_GISS-E2-1-G_hist-aer_r1i1p1...:   0%|          |0.00/8.73M [?B/s]

rlut_Amon_GISS-E2-1-G_hist-nat_r1i1p1...:   0%|          |0.00/31.8M [?B/s]

rlut_Amon_GISS-E2-1-G_hist-nat_r1i1p1...:   0%|          |0.00/31.1M [?B/s]

rsut_Amon_GISS-E2-1-G_hist-aer_r1i1p1...:   0%|          |0.00/31.8M [?B/s]

rsut_Amon_GISS-E2-1-G_hist-aer_r1i1p1...:   0%|          |0.00/31.1M [?B/s]

rlut_Amon_GISS-E2-1-G_hist-nat_r1i1p1...:   0%|          |0.00/31.1M [?B/s]

rlut_Amon_GISS-E2-1-G_hist-nat_r1i1p1...:   0%|          |0.00/8.73M [?B/s]

rsut_Amon_GISS-E2-1-G_hist-nat_r1i1p1...:   0%|          |0.00/31.1M [?B/s]

rsut_Amon_GISS-E2-1-G_hist-nat_r1i1p1...:   0%|          |0.00/31.8M [?B/s]

rsut_Amon_GISS-E2-1-G_hist-nat_r1i1p1...:   0%|          |0.00/31.1M [?B/s]

rsut_Amon_GISS-E2-1-G_hist-nat_r1i1p1...:   0%|          |0.00/8.73M [?B/s]

rsut_Amon_GISS-E2-1-G_hist-aer_r1i1p1...:   0%|          |0.00/31.1M [?B/s]

rsut_Amon_GISS-E2-1-G_hist-aer_r1i1p1...:   0%|          |0.00/8.73M [?B/s]

rlut_Amon_CESM2_hist-aer_r1i1p1f1_gn_...:   0%|          |0.00/83.9M [?B/s]

rlut_Amon_CESM2_hist-aer_r1i1p1f1_gn_...:   0%|          |0.00/84.0M [?B/s]

rlut_Amon_CESM2_hist-aer_r1i1p1f1_gn_...:   0%|          |0.00/84.0M [?B/s]

rlut_Amon_CESM2_hist-aer_r1i1p1f1_gn_...:   0%|          |0.00/25.2M [?B/s]

rsut_Amon_CESM2_hist-aer_r1i1p1f1_gn_...:   0%|          |0.00/90.4M [?B/s]

rsut_Amon_CESM2_hist-aer_r1i1p1f1_gn_...:   0%|          |0.00/90.4M [?B/s]

rsut_Amon_CESM2_hist-aer_r1i1p1f1_gn_...:   0%|          |0.00/90.5M [?B/s]

rsut_Amon_CESM2_hist-aer_r1i1p1f1_gn_...:   0%|          |0.00/27.2M [?B/s]

rlut_Amon_CESM2_hist-nat_r1i1p1f1_gn_...:   0%|          |0.00/84.0M [?B/s]

rlut_Amon_CESM2_hist-nat_r1i1p1f1_gn_...:   0%|          |0.00/84.0M [?B/s]

rlut_Amon_CESM2_hist-nat_r1i1p1f1_gn_...:   0%|          |0.00/83.9M [?B/s]

rlut_Amon_CESM2_hist-nat_r1i1p1f1_gn_...:   0%|          |0.00/25.2M [?B/s]

rsut_Amon_CESM2_hist-nat_r1i1p1f1_gn_...:   0%|          |0.00/90.4M [?B/s]

rsut_Amon_CESM2_hist-nat_r1i1p1f1_gn_...:   0%|          |0.00/90.4M [?B/s]

rsut_Amon_CESM2_hist-nat_r1i1p1f1_gn_...:   0%|          |0.00/90.4M [?B/s]

rsut_Amon_CESM2_hist-nat_r1i1p1f1_gn_...:   0%|          |0.00/27.2M [?B/s]

rlut_Amon_NorESM2-LM_hist-aer_r1i1p1f...:   0%|          |0.00/4.57M [?B/s]

rlut_Amon_NorESM2-LM_hist-aer_r1i1p1f...:   0%|          |0.00/4.57M [?B/s]

rlut_Amon_NorESM2-LM_hist-aer_r1i1p1f...:   0%|          |0.00/4.57M [?B/s]

rlut_Amon_NorESM2-LM_hist-aer_r1i1p1f...:   0%|          |0.00/4.57M [?B/s]

rlut_Amon_NorESM2-LM_hist-aer_r1i1p1f...:   0%|          |0.00/2.77M [?B/s]

rsut_Amon_NorESM2-LM_hist-aer_r1i1p1f...:   0%|          |0.00/4.73M [?B/s]

rlut_Amon_GFDL-ESM4_hist-aer_r1i1p1f1...:   0%|          |0.00/159M [?B/s]

rsut_Amon_GFDL-ESM4_hist-aer_r1i1p1f1...:   0%|          |0.00/171M [?B/s]

rlut_Amon_GFDL-ESM4_hist-aer_r1i1p1f1...:   0%|          |0.00/1.64M [?B/s]

rlut_Amon_GFDL-ESM4_hist-aer_r1i1p1f1...:   0%|          |0.00/111M [?B/s]

rsut_Amon_GFDL-ESM4_hist-aer_r1i1p1f1...:   0%|          |0.00/120M [?B/s]

rsut_Amon_GFDL-ESM4_hist-aer_r1i1p1f1...:   0%|          |0.00/1.76M [?B/s]

rlut_Amon_GFDL-ESM4_hist-nat_r1i1p1f1...:   0%|          |0.00/159M [?B/s]

rlut_Amon_GFDL-ESM4_hist-nat_r1i1p1f1...:   0%|          |0.00/112M [?B/s]

rlut_Amon_GFDL-ESM4_hist-nat_r1i1p1f1...:   0%|          |0.00/1.64M [?B/s]

rsut_Amon_GFDL-ESM4_hist-nat_r1i1p1f1...:   0%|          |0.00/171M [?B/s]

rsut_Amon_GFDL-ESM4_hist-nat_r1i1p1f1...:   0%|          |0.00/120M [?B/s]

rsut_Amon_GFDL-ESM4_hist-nat_r1i1p1f1...:   0%|          |0.00/1.76M [?B/s]

/Users/sf20/opt/anaconda3/envs/damip/lib/python3.12/site-packages/intake_esgf/catalog.py:685: UserWarning: We could not download your entire catalog, missed={'CMIP6.DAMIP.NCC.NorESM2-LM.hist-nat.r1i1p1f1.Amon.rsut.gn', 'CMIP6.DAMIP.CSIRO-ARCCSS.ACCESS-CM2.hist-nat.r1i1p1f1.Amon.rsut.gn', 'CMIP6.DAMIP.E3SM-Project.E3SM-2-0.hist-nat.r1i1p1f1.Amon.rsut.gr', 'CMIP6.DAMIP.NCC.NorESM2-LM.hist-nat.r1i1p1f1.Amon.rlut.gn'}
  warnings.warn(f"We could not download your entire catalog, {missed=}")

DatasetLoadError: We were unable to load data for these keys:
- CMIP6.DAMIP.NCC.NorESM2-LM.hist-nat.r1i1p1f1.Amon.rsut.gn
- CMIP6.DAMIP.CSIRO-ARCCSS.ACCESS-CM2.hist-nat.r1i1p1f1.Amon.rsut.gn
- CMIP6.DAMIP.E3SM-Project.E3SM-2-0.hist-nat.r1i1p1f1.Amon.rsut.gr
- CMIP6.DAMIP.NCC.NorESM2-LM.hist-nat.r1i1p1f1.Amon.rlut.gn
This could be for a few reasons:
- We failed to find file access information for these datasets.
- All the access links we found failed. The data nodes may be offline.
For more information, consult the session log 'print(cat.session_log())'.

In [16]:
cat.search(
    activity_id="DAMIP",
    activity_drs="DAMIP",
    variable_id=["rlut", "rsut"],
    experiment_id=["hist-aer", ],#"hist-nat"],
    source_id=['E3SM-2-0'],
    member_id="r1i1p1f1", 
    table_id="Amon"
)

dsd = cat.to_dataset_dict()

   Searching indices:   0%|          |0/1 [       ?index/s]

Get file information:   0%|          |0/1 [       ?index/s]

Downloading 441.1 [Mb]...

Adding cell measures:   0%|          |0/2 [     ?dataset/s]

In [18]:
cat.search(
    activity_id="DAMIP",
    activity_drs="DAMIP",
    variable_id="ts",
    experiment_id=["hist-aer", "hist-nat"],
    source_id=['HadGEM3-GC31-LL'],
    member_id="r1i1p1f3", 
    table_id="Amon"
)

dsd = cat.to_dataset_dict()

   Searching indices:   0%|          |0/1 [       ?index/s]

Get file information:   0%|          |0/1 [       ?index/s]

Downloading 232.4 [Mb]...

ts_Amon_HadGEM3-GC31-LL_hist-aer_r1i1...:   0%|          |0.00/48.3M [?B/s]

ts_Amon_HadGEM3-GC31-LL_hist-nat_r1i1...:   0%|          |0.00/67.9M [?B/s]

ts_Amon_HadGEM3-GC31-LL_hist-aer_r1i1...:   0%|          |0.00/67.9M [?B/s]

ts_Amon_HadGEM3-GC31-LL_hist-nat_r1i1...:   0%|          |0.00/48.3M [?B/s]

Adding cell measures:   0%|          |0/2 [     ?dataset/s]

found the following matches with the input file in xarray's IO backends: ['netcdf4', 'h5netcdf']. But their dependencies may not be installed, see:
https://docs.xarray.dev/en/stable/user-guide/io.html
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html

/Users/sf20/opt/anaconda3/envs/damip/lib/python3.12/site-packages/intake_esgf/catalog.py:772: UserWarning: xarray threw an exception opening these files: [PosixPath('CMIP6/CMIP/MOHC/HadGEM3-GC31-LL/piControl/r1i1p1f1/fx/areacella/gn/v20190709/areacella_fx_HadGEM3-GC31-LL_piControl_r1i1p1f1_gn.nc')]
  warnings.warn(f"xarray threw an exception opening these files: {files}")

DatasetInitError: xarray threw an exception while loading these keys: ['CMIP6.CMIP.MOHC.HadGEM3-GC31-LL.piControl.r1i1p1f1.fx.areacella.gn']